# Generated by Django 5.2.8 on 2025-11-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('ai', 'AI Lesson')], default='recorded', max_length=20),
        ),
    ]
