const mockCourses = [
  {
    id: 1,
    title: "Modern React for Beginners to Advanced",
    instructor: "John Carter",
    level: "Beginner",
    thumbnail: "https://images.unsplash.com/photo-1581090700227-1e37b190418e",
    short_description: "Learn modern React 18 with hooks, routing, and clean architecture.",
    description: "Build real apps with React 18, hooks, context, router, and best practices.",
    type: "recorded",
  },
  {
    id: 2,
    title: "Complete Django Backend Mastery",
    instructor: "Sarah Williams",
    level: "Intermediate",
    thumbnail: "https://images.unsplash.com/photo-1559027615-ce3a8a92b8e9",
    short_description: "Build production-ready backends using Django, DRF, and JWT.",
    description: "From models to APIs—deployable Django backends with auth, CORS, and tests.",
    type: "recorded",
  },
  {
    id: 3,
    title: "Fullstack JavaScript Developer Roadmap",
    instructor: "Michael Lee",
    level: "Advanced",
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    short_description: "Master Node, Express, MongoDB, and build real production apps.",
    description: "End-to-end JS: backend, frontend, and cloud to ship production apps.",
    type: "recorded",
  },
  {
    id: 4,
    title: "AI Foundations: Machine Learning & Deep Learning",
    instructor: "Emily Parker",
    level: "Intermediate",
    thumbnail: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    short_description: "Build ML models, neural networks, and AI pipelines from scratch.",
    description: "Supervised, unsupervised, and neural networks with practical projects.",
    type: "ai",
  },
  {
    id: 5,
    title: "Next.js & Tailwind CSS from Zero to Pro",
    instructor: "Nora Ahmed",
    level: "Beginner",
    thumbnail: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    short_description: "Build blazing-fast React apps with Next.js and Tailwind.",
    description: "Routing, data fetching, SEO, and beautiful UIs with Tailwind.",
    type: "recorded",
    category: "Web Development",
  },
  {
    id: 6,
    title: "Practical Data Science with Python",
    instructor: "Dr. Kevin Zhou",
    level: "Intermediate",
    thumbnail: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4",
    short_description: "Pandas, NumPy, visualization, and ML pipelines.",
    description: "Hands-on data analysis and ML workflows in Python.",
    type: "recorded",
    category: "Data Science",
  },
  {
    id: 7,
    title: "AI Lesson: Understanding Transformers",
    instructor: "AI Studio",
    level: "Intermediate",
    thumbnail: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    short_description: "An AI-generated lesson explaining transformer architectures.",
    description: "Self-attention, positional encoding, and applications.",
    type: "ai",
    category: "AI & ML",
  },
  {
    id: 8,
    title: "Flutter for Mobile Apps",
    instructor: "Priya Singh",
    level: "Beginner",
    thumbnail: "https://images.unsplash.com/photo-1518779578993-ec3579fee39f",
    short_description: "Build beautiful cross-platform apps with Flutter.",
    description: "Widgets, state management, and publishing your app.",
    type: "recorded",
    category: "Mobile Apps",
  },
  {
    id: 9,
    title: "Cloud Basics: AWS for Developers",
    instructor: "Tom Harris",
    level: "Beginner",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    short_description: "Compute, storage, and networking essentials on AWS.",
    description: "EC2, S3, IAM, and deploying your first app.",
    type: "recorded",
    category: "Cloud",
  },
  {
    id: 10,
    title: "AI Lesson: SQL Query Optimization",
    instructor: "AI Studio",
    level: "Advanced",
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    short_description: "Performance tips for complex SQL queries.",
    description: "Indexes, execution plans, and denormalization trade-offs.",
    type: "ai",
    category: "Data Science",
  },
];

export default mockCourses;
